name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
        default: '0.0.0'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the application
        id: build
        run: |
          echo '${{ secrets.ENV_TS }}' > ./Application/env.ts
          docker-compose build client_mobile
      - name: Create artifact
        id: artifact
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: ./